### ISSUE TITLE
Ticking Entity Error: Tomato tried to grow on wrong block?

### ISSUE THREAD

**Issue by IdrisQe** [DawnTeamMC/CommonExpansionFoodstuffs#5]
Not sure what was happening here. I was just in my inventory on a new world, opened REI, and suddenly crashed, however the issue seems to be that a tomato that was already planted somewhere tried to grow onto a speleothem from Wild World rather than something menu-related?

https://gist.githubusercontent.com/natanfudge/85141847742a82830abf3b6bb6882082/raw/cd2dad30108c4e4f0d6c87d34e953e8b423f5cb5/crash.txt

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 28/02/21 3:29 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{wildworld:sandstone_speleothem}
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at net.minecraft.state.State.get(State:95)
	at com.hugman.ce_foodstuffs.objects.block.TomatoesBlock.canPlaceAt(TomatoesBlock.java:151)
	at net.minecraft.entity.ItemEntity.handler$cah002$tick(ItemEntity:2560)
	at net.minecraft.entity.ItemEntity.tick(ItemEntity:95)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
	at net.minecraft.world.World.tickEntity(World:561)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
	at net.minecraft.server.MinecraftServer.redirect$cgk000$ficUpdateSuppressionCrashTick(MinecraftServer:5207)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.handler$epb000$modifiedRunLoop(MinecraftServer:9810)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 1824
	Entity Name: Tomato
	Entity's Exact location: 278.73, 33.00, 39.88
	Entity's Block location: World: (278,33,39), Chunk: (at 6,2,7 in 17,2; contains blocks 272,0,32 to 287,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {Motion:[0.0010612246143462932d,0.0d,0.0d],WetTimer:0,Health:5s,Invulnerable:0b,Air:300s,OnGround:1b,PortalCooldown:0,Rotation:[17.463242f,0.0f],FallDistance:0.0f,Item:{id:"ce_foodstuffs:tomato",Count:1b},Pos:[278.73003326677605d,33.0d,39.875d],PickupDelay:0s,BoundingBox:[278.60503326677605d,33.0d,39.75d,278.85503326677605d,33.25d,40.0d],Fire:-1s,UUID:[I;206631782,-495237518,-1319126967,167502900],Age:20s,TinyTweaksFireType:"NORMAL"}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:564)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.redirect$cgk000$ficUpdateSuppressionCrashTick(MinecraftServer.java:5207)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.handler$epb000$modifiedRunLoop(MinecraftServer.java:9810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)
-- Affected level --
Details:
	All players: 1 total; [class_3222['HickoryHazelyPip'/308, l='ServerLevel[Arkonyhm]', x=240.49, y=91.00, z=8.98]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (261,85,4), Chunk: (at 5,5,4 in 16,0; contains blocks 256,0,0 to 271,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3600 game time, 3600 day time
	Level name: Arkonyhm
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 63852 (now: false), thunder time: 39134 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2549272736 bytes (2431 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 21 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Suspected Mods: Common Expansion: Foodstuffs (ce_foodstuffs)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.9
		adorn: Adorn 1.13.0+1.16.5
		allure: Allure 1.2.8
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		aquarius: Aquarius 1.0.3
		architectury: Architectury 1.8.128
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		backslot: BackSlot 1.1.9
		bedrockify: BedrockIfy 0.2.5
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.7
		betterthanmending: BetterThanMending 1.3.0
		betterthirdperson: Better Third Person 1.3.0
		bewitchment: Bewitchment 1.16.5-2
		biomemakeover: Biome Makeover 1.16.4-1.2.11
		campanion: Campanion 1.3.5
		cardinal-components-base: Cardinal Components API (base) 2.7.12
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.12
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.12
		carpet: Carpet Mod in Fabric 1.4.28
		carpet-extra: Carpet Extra 1.4.27
		castle_dungeons: Castle Dungeons 2.2
		cdsam: Survival Additions 1.3.2-Fabric-1.16.5
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1.3
		charm: Charm 2.3.2
		charmonium: Charmonium 2.3.2
		cinderscapes: Cinderscapes 1.3.3
		classicalart: Classical Art 1.1.0
		clear-skies: Clear Skies 1.5.55
		climbable: Climbable 0.2.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		cpas: conveniently placed armor slots 1.3.0+1.16.5
		creeperspores: Creeper Spores 1.4.1
		croptopia: Croptopia 1.2.0
		crowmap: Crowmap 1.0.1
		crumbs: Crumbs 1.0.6
		curses: Curses 1.5.1
		darkness: True Darkness 1.6.58
		darkpaintings: Dark Paintings 3.0.1
		dawn: Dawn API 1.7
		desolation: Desolation 1.1.0
		direbats: Direbats 1.1.0+1.16.5-fabric
		dual_riders: DualRiders 1.0.5
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		enchantmentdescriptions: Enchantment Descriptions 2.0.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.0
		entityculling: EntityCulling-Fabric 1.0.2
		extraalchemy: Extra Alchemy 1.3.1
		extradoors: ExtraDoors 1.8.2-1.16.2
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.30+build.2
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabrication: Fabrication 1.3.3
		fabricloader: Fabric Loader 0.11.2
		fallingtree: FallingTree 2.10.2
		ferritecore: FerriteCore 2.0.2
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.22
		healthoverlay: Health Overlay 3.6.14
		herdspanic: Herds Panic 1.0.1
		horsestatsvanilla: Horse Stats Vanilla 4.1.6
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.4.5
		impersonate: Impersonate 2.1.0
		itemmodelfix: Item Model Fix 1.0.0
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kirin: Kirin UI 1.7-1.16.2
		krypton: Krypton 0.1.2
		lakeside: Lakeside 1.0.3+1.16.4
		lepton: Lepton-Fabric 1.16.5-1.0.0
		lessannoyingpiglins: Less Annoying Piglins 1.0.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.8.0
		lithium: Lithium 0.6.4
		lock_minecart_view: Better minecart rotation 1.2.1
		maelstrom_library: Maelstrom Library 1.0-1.16.5
		microdurability: microDurability 0.3.0+1.16.3
		minecraft: Minecraft 1.16.5
		miniextras: Mini Extras Mod 1.2.1
		mobblindness: Mob Blindness 1.0.0
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.2-1.16.5
		modmenu: Mod Menu 1.16.8
		morerespawnanchors: More Respawn Anchors 1.0.1
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		nookbuild: NookBuild 1.4.0
		notenoughcrashes: Not Enough Crashes 3.1.7
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.0.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.0.1
		overpowered_mending: Overpowered Mending 2.2.3
		overworld_two: Overworld 2 1.0.4
		patchouli: Patchouli 1.16.4-50-FABRIC
		peepingcreepers: Peeping Creepers 1.1
		pehkui: Pehkui 1.7.1+21w03a
		phosphor: Phosphor 0.7.1+build.11
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.10-1.16.5
		potiondescriptions: Potion Descriptions fabric-1.1
		presencefootsteps: Presence Footsteps r29+1.16.4
		pride: Pride Lib 1.0.0+1.16
		programmerartinjector: Programmer Art Injector 1.2.1
		randompatches: RandomPatches 2.4.5-fabric
		ratsmischief: Rat's Mischief 1.0.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		recipeconditions: Fabric Recipe Conditions 0.4.0
		repurposed_structures: Repurposed Structures 1.16.5-1.8.3
		requiem: Requiem 1.5.0
		requiemapi: Requiem-API 1.5.0
		reroll: Reroll 1.2.0-1.16.5
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.10.184
		roughlyenoughitems-api: REI (API) 5.10.184
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
		roughlyenoughitems-runtime: REI (Runtime) 5.10.184
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		satin: Satin 1.5.1
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		sheepconsistency: Sheep Consistency 1.0.2
		shulkercharm: Shulker Charm 1.1.3+1.16.5
		smoothboot: Smooth Boot 1.16.4-1.4.0
		spellbound: Spellbound 1.2.0
		stepup: StepUp 1.16.5-fabric0.30.0-1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		terrestria: Terrestria 2.2.0
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.3.0
		tillitbreaks: Till it Breaks 0.1
		tinytweaks: TinyTweaks 1.2.1
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		tweed: Tweed API 3.0.0-beta.22
		vanguard: Vanguard 1.0.5
		vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
		vanillatweaks: VanillaTweaks 1.16.4-1.0.6
		villagernames: Villager Names 1.6.0
		voyager: Voyager 1.0.0
		waystones: Waystones 1.1.1.1
		wild_explorer: Wild Explorer 1.3.2
		wildworld: Wild World 2.0.0+1.16.5
		xaerominimap: Xaero's Minimap 21.4.0
		xaeroworldmap: Xaero's World Map 1.12.0
		yungsapi: YUNG's API 1.16.5-Fabric-2
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['HickoryHazelyPip'/308, l='ServerLevel[Arkonyhm]', x=240.49, y=91.00, z=8.98]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by Hugman76** [comment]
This issue does not come from our mod. It seems like an entity (a tomato entity item) was dropped inside of a `wildworld:sandstone_speleothem` block's hitbox and a mod tried to place a tomato crop block there.
It's purely a coincidence that this is an item from our mods. 
I have no idea what mod tries to do this.
